### ISSUE TITLE
How to deal with the 

### ISSUE THREAD

**Issue by SorryGeats** [TQTQliu/MVSGaussian#18]
Hello, when I run the command `ython train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root dataset/<>test_dataset.data_root dataset/<>` on my own dataset, the erroe is like:

`Traceback (most recent call last):
  File "train_net.py", line 151, in <module>
    main()
  File "train_net.py", line 143, in main
    train(cfg, network)
  File "train_net.py", line 51, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/train/trainers/trainer.py", line 49, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/datasets/colmap/mvsgs.py", line 95, in __getitem__
    src_views = random.sample(src_views, input_views_num)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative`

How can I fix the problem?

**Comment by TQTQliu** [comment]
Hello, the error `Sample larger than population or is negative` is caused by `src_views = random.sample(src_views, input_views_num)` in File "lib/datasets/colmap/mvsgs.py", line 95.
For `random.sample(src_views, input_views_num)`, where `src_views` is a list, and **`len(src_views)>=input_views_num`** must be satisfied. Otherwise, it will lead to the above error. Please check it.

**Comment by SorryGeats** [comment]
I‘ve added ` # 确保 input_views_num 不超过 src_views 的长度
            if input_views_num > len(src_views):
                print(f"Warning: input_views_num ({input_views_num}) is greater than the length of src_views ({len(src_views)}). Adjusting 
                input_views_num to {len(src_views)}.")
                input_views_num = len(src_views)` after `
            if self.split == 'train':
                if np.random.random() < 0.1:
                   src_views = src_views + [tar_view]`,
but it turns out that 
`Traceback (most recent call last):
  File "train_net.py", line 151, in <module>
    main()
  File "train_net.py", line 143, in main
    train(cfg, network)
  File "train_net.py", line 51, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/train/trainers/trainer.py", line 49, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/datasets/colmap/mvsgs.py", line 106, in __getitem__
    src_views = random.sample(src_views, input_views_num)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative`

**Comment by TQTQliu** [comment]
I know what you mean. I wonder if you changed it to look like this:
```
if self.split == 'train':
    if np.random.random() < 0.1:
        src_views = src_views + [tar_view]
    if input_views_num > len(src_views):
        input_views_num = len(src_views)
    src_views = random.sample(src_views, input_views_num)
scene_info = self.scene_infos[scene]
```
If so, I think it can work. 


But I would suggest checking why `input_views_num > len(src_views)` occurs. In the default Settings, for training, `input_views_num` could be 2,3 or 4, which is set [here](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/configs/mvsgs/dtu_pretrain.yaml#L21). And the `src_views` is defined [here](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/lib/datasets/colmap/mvsgs.py#L58).

**Comment by SorryGeats** [comment]
OK，I‘ll have a check

**Comment by SorryGeats** [comment]
Sorry to bother you, but now with the same command, it turns out that `(mvsgs) sunzhenyu@mercury:~/Projects/MVSGaussian$ python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root dataset/MVDiffusion_demo test_dataset.data_root dataset/MVDiffusion_demo
Workspace:  .
configs/mvsgs/dtu_pretrain.yaml
configs/mvsgs/colmap_eval.yaml
EXP NAME:  dtu_pretrain
/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
load model: ./trained_model/mvsgs/dtu_pretrain/latest.pth
Traceback (most recent call last):
  File "train_net.py", line 151, in <module>
    main()
  File "train_net.py", line 143, in main
    train(cfg, network)
  File "train_net.py", line 51, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/train/trainers/trainer.py", line 55, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/train/losses/mvsgs.py", line 18, in forward
    output = self.net(batch)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/networks/mvsgs/network.py", line 78, in forward
    feats = self.forward_feat(batch['src_inps'])
  File "lib/networks/mvsgs/network.py", line 60, in forward_feat
    feat2, feat1, feat0 = self.feature_net(x)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/networks/mvsgs/feature_net.py", line 28, in forward
    conv0 = self.conv0(x)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/networks/mvsgs/utils.py", line 44, in forward
    return self.relu(self.bn(self.conv(x)))
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sunzhenyu/anaconda3/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 460, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution`

while two hours before, it could run but finally terminates early because of my mannual excepted interuption.

I'm still working for the reason for why `input_views_num > len(src_views)` occurs, anticipating for your constructive suggestions!

**Comment by TQTQliu** [comment]
The error `RuntimeError: Unable to find a valid cuDNN algorithm to run convolution` is generally caused by insufficient memory of the gpu. You can check it and specify gpu index [here](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/configs/mvsgs/dtu_pretrain.yaml#L2).

**Comment by SorryGeats** [comment]
OK，now it seems work！
