### ISSUE TITLE
 “win_size exceeds image extent”

### ISSUE THREAD

**Issue by xdh096** [TQTQliu/MVSGaussian#30]
Traceback (most recent call last):
  File "/mnt/sda/xdh/MVS-GS/MVSGaussian/run.py", line 98, in <module>
    globals()['run_' + args.type]()
  File "/mnt/sda/xdh/MVS-GS/MVSGaussian/run.py", line 82, in run_evaluate
    evaluator.evaluate(output, batch)
  File "lib/evaluators/mvsgs.py", line 73, in evaluate
    ssim_item = ssim(gt_rgb[b], pred_rgb[b], multichannel=True)
  File "/mnt/sda/xdh/env/mvsgs/lib/python3.10/site-packages/skimage/metrics/_structural_similarity.py", line 178, in structural_similarity
    raise ValueError(
ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.

I can't run the code successfully, please take a look for me

**Comment by TQTQliu** [comment]
This may be an incorrect version of scikit-image, you can install `scikit-image==0.19.0`.
