### ISSUE TITLE
Error when running run.py

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#58]
Hello sir, happy Nation Day！I've met some difficulties running the run.py.
```
Workspace:  .
configs/mvsgs/dtu_pretrain.yaml
configs/mvsgs/colmap_eval.yaml
EXP NAME:  dtu_pretrain
load model: ./trained_model/mvsgs/dtu_pretrain/latest.pth
Traceback (most recent call last):
  File "run.py", line 98, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 55, in run_evaluate
    data_loader = make_data_loader(cfg, is_train=False)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/datasets/make_dataset.py", line 90, in make_data_loader
    dataset = make_dataset(cfg, is_train)
  File "/home/sunzhenyu/Projects/MVSGaussian/lib/datasets/make_dataset.py", line 39, in make_dataset
    dataset = dataset(**args)
  File "lib/datasets/colmap/mvsgs.py", line 19, in __init__
    self.build_metas()
  File "lib/datasets/colmap/mvsgs.py", line 51, in build_metas
    c2ws = c2ws[train_ids]
IndexError: index 4 is out of bounds for axis 0 with size 4
```

However, the colmap step is nothing wrong.
I don't know which part went wrong, so I'm going to ask for your constructive advice.

**Comment by TQTQliu** [comment]
This means that `train_ids` is out of bounds of `c2ws`. Please check the value of `train_ids` and the shape of `c2ws`.

**Comment by crazyzyz** [comment]
> Hello sir, happy Nation Day！I've met some difficulties running the run.py.
> 
> ```
> Workspace:  .
> configs/mvsgs/dtu_pretrain.yaml
> configs/mvsgs/colmap_eval.yaml
> EXP NAME:  dtu_pretrain
> load model: ./trained_model/mvsgs/dtu_pretrain/latest.pth
> Traceback (most recent call last):
>   File "run.py", line 98, in <module>
>     globals()['run_' + args.type]()
>   File "run.py", line 55, in run_evaluate
>     data_loader = make_data_loader(cfg, is_train=False)
>   File "/home/sunzhenyu/Projects/MVSGaussian/lib/datasets/make_dataset.py", line 90, in make_data_loader
>     dataset = make_dataset(cfg, is_train)
>   File "/home/sunzhenyu/Projects/MVSGaussian/lib/datasets/make_dataset.py", line 39, in make_dataset
>     dataset = dataset(**args)
>   File "lib/datasets/colmap/mvsgs.py", line 19, in __init__
>     self.build_metas()
>   File "lib/datasets/colmap/mvsgs.py", line 51, in build_metas
>     c2ws = c2ws[train_ids]
> IndexError: index 4 is out of bounds for axis 0 with size 4
> ```
> 
> However, the colmap step is nothing wrong. I don't know which part went wrong, so I'm going to ask for your constructive advice.

Hey bro! I hope to know how you finally dealt with it, because I also encountered this problem, your answer is very important to me, looking forward to your reply

**Comment by tvkamara** [comment]
This happens to me too on some test scenes, any idea how to fix it? What actually is c2ws?
