### ISSUE TITLE
The test runs run.py incorrectly

### ISSUE THREAD

**Issue by crazyzyz** [TQTQliu/MVSGaussian#67]
Error: 

 python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples test_dataset.scene scene2
Workspace:  .
configs/mvsgs/dtu_pretrain.yaml
configs/mvsgs/colmap_eval.yaml
EXP NAME:  dtu_pretrain
load model: ./trained_model/mvsgs/dtu_pretrain/latest.pth
Traceback (most recent call last):
  File "run.py", line 98, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 55, in run_evaluate
    data_loader = make_data_loader(cfg, is_train=False)
  File "/root/MVSGaussian/lib/datasets/make_dataset.py", line 90, in make_data_loader
    dataset = make_dataset(cfg, is_train)
  File "/root/MVSGaussian/lib/datasets/make_dataset.py", line 39, in make_dataset
    dataset = dataset(**args)
  File "lib/datasets/colmap/mvsgs.py", line 23, in __init__
    self.build_metas()
  File "lib/datasets/colmap/mvsgs.py", line 55, in build_metas
    train_ids = [j for j in range(img_len) if j not in render_ids]
  File "lib/datasets/colmap/mvsgs.py", line 55, in <listcomp>
    train_ids = [j for j in range(img_len) if j not in render_ids]
NameError: free variable 'render_ids' referenced before assignment in enclosing scope

Do I need to configure something in configs/mvsgs/colmap_eval.yaml config file because I see error because render_ids is not assigned or which file should I adjust.
Looking forward to your reply, it will help me a lot, thank you!！！！！！！！！！！

**Comment by TQTQliu** [comment]
Hello, this is the problem of the code we uploaded before, I have modified it now, please refer [here](https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/lib/datasets/colmap/mvsgs.py#L54-L59).
