### ISSUE TITLE
demo出现运行错误，ValueError: too many values to unpack

### ISSUE THREAD

**Issue by horrordor** [TQTQliu/MVSGaussian#75]
感谢作者开源。在运行您的demo时，在执行第二步
`python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples test_dataset.scene scene1`
时，出现以下问题：

``` bash
python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples test_dataset.scene scene1 save_video True
Workspace:  .
configs/mvsgs/dtu_pretrain.yaml
configs/mvsgs/colmap_eval.yaml
EXP NAME:  dtu_pretrain
load model: ./trained_model/mvsgs/dtu_pretrain/latest.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/XINGYujie_2024/miniconda3/envs/pytorch/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/XINGYujie_2024/miniconda3/envs/pytorch/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/XINGYujie_2024/miniconda3/envs/pytorch/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth
  0%|                                                                                                                                                            | 0/4 [00:00<?, ?it/s]/home/XINGYujie_2024/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                                            | 0/4 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/home/XINGYujie_2024/MVSGaussian/run.py", line 98, in <module>
    globals()['run_' + args.type]()
  File "/home/XINGYujie_2024/MVSGaussian/run.py", line 73, in run_evaluate
    network(batch)
  File "/home/XINGYujie_2024/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "lib/networks/mvsgs/network.py", line 201, in forward
    render_novel_i_0 = render(meta, b_i, world_xyz[b_i], color_out[b_i], rot_out[b_i], scale_out[b_i], opacity_out[b_i], bg_color=cfg.mvsgs.bg_color)
  File "/home/XINGYujie_2024/MVSGaussian/lib/gaussian_renderer/__init__.py", line 53, in render
    rendered_image, _ = rasterizer(
ValueError: too many values to unpack (expected 2)
```
希望作者大大能抽空帮忙解决。

另附第一步的运行结果以供参考
![微信截图_20241120165038](https://github.com/user-attachments/assets/4fc7b53c-7d73-44f3-ae8e-96910276bc6d)

**Comment by TQTQliu** [comment]
谢谢您对我们工作的关注，您可以重新安装下面这个库，类似的问题可参考[这里](https://github.com/TQTQliu/MVSGaussian/issues/41#issue-2485017405)。
```
pip install lib/submodules/diff-gaussian-rasterization
pip install lib/submodules/simple-knn
```

**Comment by horrordor** [comment]
> 谢谢您对我们工作的关注，您可以重新安装下面这个库，类似的问题可参考[这里](https://github.com/TQTQliu/MVSGaussian/issues/41#issue-2485017405)。
> 
> ```
> pip install lib/submodules/diff-gaussian-rasterization
> pip install lib/submodules/simple-knn
> ```

感谢您的回复
