### ISSUE TITLE
When I try to use 5 graphs for inference, I get an error when running train.py

### ISSUE THREAD

**Issue by datouzhan** [TQTQliu/MVSGaussian#76]
Hi, thanks for the great work! But I have some questions.
I have 5 images from different views that I want to use for inference (only four).
However, when I execute train.py, I encounter the following error:

(mvsgs) root@autodl-container-7770449125-713362b1:~/MVSGaussian# python lib/train.py  --eval --iterations 30000 -s examples/scene1 -p /examples/scene1
Optimizing ./output/scene1
Output folder: ./output/scene1
Tensorboard not available: not logging progress
Reading camera 5/5
Traceback (most recent call last):
  File "lib/train.py", line 236, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, init_ply=args.init_ply)
  File "lib/train.py", line 67, in training
    scene = Scene(dataset, gaussians, init_ply=init_ply)
  File "/root/MVSGaussian/lib/scene/__init__.py", line 51, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval, init_ply=init_ply, video=video)
  File "/root/MVSGaussian/lib/scene/dataset_readers.py", line 573, in readColmapSceneInfo
    nerf_normalization = getNerfppNorm(train_cam_infos)
  File "/root/MVSGaussian/lib/scene/dataset_readers.py", line 66, in getNerfppNorm
    center, diagonal = get_center_and_diag(cam_centers)
  File "/root/MVSGaussian/lib/scene/dataset_readers.py", line 52, in get_center_and_diag
    cam_centers = np.hstack(cam_centers)
  File "<__array_function__ internals>", line 6, in hstack
  File "/root/miniconda3/envs/mvsgs/lib/python3.7/site-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by TQTQliu** [comment]
Hi, thanks for your interest. `train_ids` may be empty. You can check [here](https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/lib/scene/dataset_readers.py#L535-L545).

**Comment by datouzhan** [comment]
Thanks for your reply, when I changed the code to train_ids = list(range(img_len))
render_ids = train_ids. It works fine.

**Comment by datouzhan** [comment]
> 您好，感谢您的关注。`train_ids`可能为空。您可以[在此处](https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/lib/scene/dataset_readers.py#L535-L545)查看。
Thanks for your reply, when I changed the code to train_ids = list(range(img_len))
render_ids = train_ids. It works fine.
